### ISSUE TITLE
Exception: Request Error!: 404 : Not Found (/mstar/daily.py)

### ISSUE THREAD

**Issue by Mik3Christ3ns3n** [omdv/robinhood-portfolio#4]
It appears the morningstar endpoint for collecting data is no longer available...

Exception: Request Error!: 404 : Not Found

Traceback (most recent call last)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/robinhood/robinhood-portfolio/app.py", line 90, in portfolio
bc = BackendClass(DATAFILE, USERFILE)
File "/home/robinhood/robinhood-portfolio/backend/backend.py", line 35, in __init__
self._validate_user_dict()
File "/home/robinhood/robinhood-portfolio/backend/backend.py", line 78, in _validate_user_dict
self.update_market_data(fresh_start=True)
File "/home/robinhood/robinhood-portfolio/backend/backend.py", line 104, in update_market_data
self._df_ord.symbol.unique(), min_date, max_date)
File "/home/robinhood/robinhood-portfolio/backend/market_data.py", line 71, in download_save_market_data
end_date.date())
File "/home/robinhood/robinhood-portfolio/backend/market_data.py", line 41, in _get_historical_prices
pf = web.DataReader(tickers, 'morningstar', start_date, end_date)
File "/usr/lib/python3.5/site-packages/pandas_datareader/data.py", line 391, in DataReader
session=session, interval="d").read()
File "/usr/lib/python3.5/site-packages/pandas_datareader/mstar/daily.py", line 219, in read
df = self._dl_mult_symbols(symbols=symbols)
File "/usr/lib/python3.5/site-packages/pandas_datareader/mstar/daily.py", line 130, in _dl_mult_symbols
resp.status_code, resp.reason))
Exception: Request Error!: 404 : Not Found

**Comment by omdv** [comment]
Yes, Morningstar is deprecated - https://github.com/pydata/pandas-datareader/issues/557
The next one to try is IEX. Will update the code in a few days or you can fork and update yourself.

**Comment by omdv** [comment]
https://github.com/omdv/robinhood-portfolio/commit/1711cf204271e1838e0cac85b0e13de02281dc7c
