### ISSUE TITLE
Trying to run in a conda env with most updated pandas-0.23.3

### ISSUE THREAD

**Issue by trevorwelch** [omdv/robinhood-portfolio#5]
```
$ python3 app.py
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from backend.backend import BackendClass
  File "/Users/tw/Github/robinhood-portfolio/backend/backend.py", line 5, in <module>
    from backend.robinhood_data import RobinhoodData
  File "/Users/tw/Github/robinhood-portfolio/backend/robinhood_data.py", line 3, in <module>
    from pandas.core.tools.datetimes import normalize_date
ImportError: cannot import name 'normalize_date'
```

**Comment by omdv** [comment]
I won't be converting it to latest pandas, as apart from `normalize_date` it will require moving away from Panels, which I don't have time to do. There are also no benefits of using latest pandas for this particular application. You will have to use a supplied `requirements.txt` to create a dedicated conda environment or use docker.
