### ISSUE TITLE
502 bad gateway? 

### ISSUE THREAD

**Issue by jonchui** [omdv/robinhood-portfolio#6]
After following instructions, going to localhost:8080 i get this error

```
builtins.Exception
Exception: Request Error!: 502 : Bad Gateway

Traceback (most recent call last)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/jonchui/code/GitHub/robinhood-portfolio/app.py", line 90, in portfolio
bc = BackendClass(DATAFILE, USERFILE)
File "/Users/jonchui/code/GitHub/robinhood-portfolio/backend/backend.py", line 35, in __init__
self._validate_user_dict()
File "/Users/jonchui/code/GitHub/robinhood-portfolio/backend/backend.py", line 78, in _validate_user_dict
self.update_market_data(fresh_start=True)
File "/Users/jonchui/code/GitHub/robinhood-portfolio/backend/backend.py", line 104, in update_market_data
self._df_ord.symbol.unique(), min_date, max_date)
File "/Users/jonchui/code/GitHub/robinhood-portfolio/backend/market_data.py", line 72, in download_save_market_data
end_date.date())
File "/Users/jonchui/code/GitHub/robinhood-portfolio/backend/market_data.py", line 42, in _get_historical_prices
pf = web.DataReader(tickers, 'morningstar', start_date, end_date)
File "/usr/local/lib/python3.6/site-packages/pandas_datareader/data.py", line 391, in DataReader
session=session, interval="d").read()
File "/usr/local/lib/python3.6/site-packages/pandas_datareader/mstar/daily.py", line 219, in read
df = self._dl_mult_symbols(symbols=symbols)
File "/usr/local/lib/python3.6/site-packages/pandas_datareader/mstar/daily.py", line 130, in _dl_mult_symbols
resp.status_code, resp.reason))
Exception: Request Error!: 502 : Bad Gateway
```

any ideas?

**Comment by jonchui** [comment]
is it related to morningstar being down? https://github.com/pydata/pandas-datareader/issues/557

**Comment by omdv** [comment]
I am most positive that it is related. Unfortunately a lot of services are discontinuing their live quote APIs. And I stopped being RH client, so really have no incentive to try to find a solution. Unfortunately this repo is likely obsolete now. If I'd have to find a solution, I'd probably explore the [Tiingo](https://pydata.github.io/pandas-datareader/stable/remote_data.html#tiingo)

**Comment by omdv** [comment]
Changed to TIINGO, see updated readme.
https://github.com/omdv/robinhood-portfolio/commit/1711cf204271e1838e0cac85b0e13de02281dc7c
